bookmark/urls.py
from django.urls import path
from .views import BookmarkListView, BookmarkCreateView, BookmarkDetailView, BookmarkUpdateView, BookmarkDeleteView

app_name = "bookmark"

urlpatterns = [
    path("", BookmarkListView.as_view(), name="list"),
    path("add/", BookmarkCreateView.as_view(), name="add"),
    path("detail/<int:pk>/", BookmarkDetailView.as_view(), name="detail"),
    path("update/<int:pk>/", BookmarkUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", BookmarkDeleteView.as_view(), name="delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # 1차 -> 2차 -> 3차
    # http://127.0.0.1/bookmark/?
    
    path("admin/", admin.site.urls),
    path("bookmark/", include("bookmark.urls")),
]

bookmark/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
# 모델 : 데이터베이스를 SQL 없이 다루려고 모델을 사용
# 우리가 데이터를 객체화해서 다루겠다.
# 모델 = 테이블
# 모델의 필드 = 테이블의 컬럼
# 인스턴스 = 테이블의 레코드
# 필드의 값(인스턴스의 필드값) = 레코드의 컬럼 데이터값
class Bookmark(models.Model):
    site_name = models.CharField(max_length=100)
    url = models.URLField("Site URL")
    # 필드의 종류가 결정하는 것
    # 1. 데이터베이스의 컬럼 종류
    # 2. 제약 사항 (몇글자까지) 
    # 3. Form의 종류
    # 4. Form에서 제약 사항
    
    
    def __str__(self):
        return "이름 : " + self.site_name + ", 주소 : " + self.url
    # 모델을 만들었다 => 데이터베이스에 어떤 데이터들을 어떤 형태로 넣을지 결정!
    # makemigrations => 모델의 변경사항을 추적해서 기록
    # 마이그레이션(migrate) => 데이터베이스에 모델의 내용을 반영(테이블 생성)

    def get_absolute_url(self):
        return reverse("detail", args=[str(self.id)])

bookmark/views.py
from django.shortcuts import render

# Create your views here.
#CRUD : Create, Read, Update, Delete
#List

# 클래스형 뷰, 함수형 뷰
# 웹 페이지에 접속한다. -> 페이지를 본다.
# URL을 입력 -> 웹 서버가 뷰를 찾아서 동작시킨다. -> 응답

from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView

from django.urls import reverse_lazy

from .models import Bookmark

class BookmarkListView(ListView):
    model = Bookmark

class BookmarkCreateView(CreateView):
    model = Bookmark
    fields = "__all__"
    template_name_suffix = "_create"
    success_url = reverse_lazy("bookmark:list")

class BookmarkDetailView(DetailView):
    model = Bookmark

class BookmarkUpdateView(UpdateView):
    model = Bookmark
    fields = "__all__"
    template_name_suffix = "_update"
    
class BookmarkDeleteView(DeleteView):
    model = Bookmark
    fields = "__all__"
    success_url = reverse_lazy("bookmark:list")

bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Confirm Delete{% endblock %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <div class="alert alert-danger">
        Do you want to delete Bookmark "{{ bookmark }}"?
        <input type="submit" value="Delete" class="btn btn-danger btn-sm">
    </div>
</form>
{% endblock %}

bookmark/templates/bookmark/bookmark_create.html
{% extends 'base.html' %}

{% block title %}Create{% endblock %}
{% block content %}
<form accept="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add" class="btn btn-info btn-sm">
</form>
{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}

{% block title %}Detail{% endblock %}
{% block content %}
{{ object.site_name }}<br/>
{{ object.url }}
{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}

{% block title %}Bookmark List{% endblock %}
{% block content %}
<div class="btn-group">
    <a href="{% url 'bookmark:add' %}" class="btn btn-info">Add Bookmark</a>
</div>
<p></p>
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Site</th>
            <th scope="col">URL</th>
            <th scope="col">Modify</th>
            <th scope="col">Delete</th>
        </tr>
    </thead>
    <tbody>
        {% for bookmark in object_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td><a href="{% url 'bookmark:detail' pk=bookmark.id %}">{{ bookmark.site_name }}</a></td>
            <td><a href="{{ bookmark.url }}" target="_blank">{{ bookmark.url }}</a></td>
            <td><a href="{% url 'bookmark:update' pk=bookmark.id %}" class="btn btn-success btn-sm">Modify</a></td>
            <td><a href="{% url 'bookmark:delete' pk=bookmark.id %}" class="btn btn-danger btn-sm">Delete</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

bookmark/templates/bookmark/bookmark_update.html
{% extends 'base.html' %}

{% block title %}Bookmark Update{% endblock %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" class="btn btn-success btn-sm">
</form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="kr">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Django Bookmark</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-targe="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapese navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home<span class="sr-only"></span></a>
                    </li>
                </ul>
            </div>
        </nav>
        <p></p>
        <div class="row">
            <div class="col">
                {% block content %}
                {% endblock %}
            </div>
        </div>
        
    </div>
</body>
</html>